id = "hercscript"
name = "Hercules Script"
description = "Comprehensive language support for Hercules (herc.ws) scripting language with syntax highlighting, snippets, and smart code editing features."
version = "0.3.0"
schema_version = 1
authors = ["Vietlubu"]
repository = "https://github.com/vietlubu/zed-hercscript"

[grammars.hercscript]
repository = "https://github.com/vietlubu/tree-sitter-hercscript"
rev = "a0e884d11ecaefb036e117db18569d2c4bc93ddf"
