id = "hercscript"
name = "Hercules Script"
description = "Comprehensive language support for Hercules (herc.ws) scripting language with syntax highlighting, snippets, and smart code editing features."
version = "0.1.0"
schema_version = 1
authors = ["Vietlubu"]
repository = "https://github.com/vietlubu/zed-hercscript"

[grammars.hercscript]
repository = "https://github.com/vietlubu/tree-sitter-hercscript"
rev = "4085d39df643d39d96c7a47c23e628cf54ad3f95"
